---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-ubuntu
    image: 'mpaivabarbosa/molecule-systemd-ubuntu:latest'
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true
    command: /usr/sbin/init
    
  - name: instance-debian
    image: 'mpaivabarbosa/molecule-systemd-debian:latest'
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true
    command: /lib/systemd/systemd
provisioner:
  name: ansible
verifier:
  name: ansible
